
name: Terraform SonarQube Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read  

jobs:
  terraform-sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token from secrets
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # SonarQube token from secrets
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
        with:
          args: |
            -Dsonar.organization=karthikeya142
            -Dsonar.projectKey=karthikeya142_cloud_migration
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.language=terraform
            -Dsonar.exclusions=**/*.md

        
